### PR TITLE
Merging from branch: Total supsnded matter, Chrolophil anomaly, Sea surface temperature

### PR DESCRIPTION
**Pull request by AlessandroScremin**
N3a2_chl_concentration_tri_esa N3a2_total_suspended_matter_tri_esa N3a2_sea_surface_temperature

### CODE REVIEW

**Review by lubojr — APPROVED** [review]

**Comment by lubojr** [comment]
@AlessandroScremin there was a regression on our side, but looking at the WFS request for TSMNN, there are data only for 4 locations per each time date: https://services.sentinel-hub.com/ogc/wfs/0635c213-17a1-48ee-aef7-9d1731695a54?REQUEST=GetFeature&srsName=EPSG:4326&TIME=1900-01-01/3000-02-01&outputformat=application/json&TYPENAMES=DSS10-698ade22-bc30-44d1-8751-159ee135f998&BBOX=-180,-90,180,90

compared to 6 for SST: 
https://services.sentinel-hub.com/ogc/wfs/0635c213-17a1-48ee-aef7-9d1731695a54?REQUEST=GetFeature&srsName=EPSG:4326&TIME=1900-01-01/3000-02-01&outputformat=application/json&TYPENAMES=DSS10-92780d01-126f-4827-80f8-4e561dd8e228&BBOX=-180,-90,180,90

Could you please check the ingestion?

**Review by lubojr — CHANGES_REQUESTED** [review]
Review needed for TSMNN ingestion (entries for 2 new locations are not showing in STAC/WFS response), which makes collection have invalid spatial and temporal extent.
If those two new locations are not supposed to have TSMNN data, they need to be removed from the locations array in YAML file

**Comment by AlessandroScremin** [comment]
> Review needed for TSMNN ingestion (entries for 2 new locations are not showing in STAC/WFS response), which makes collection have invalid spatial and temporal extent. If those two new locations are not supposed to have TSMNN data, they need to be removed from the locations array in YAML file

you were right.
Indeed TSMNN don't have the new AOIs...

**Review by lubojr — APPROVED** [review]
Now loads fine. Thanks for the support. We shall merge it together with Federico's PRs to have just one build happening.

**Comment by AlessandroScremin** [comment]
> Now loads fine. Thanks for the support. We shall merge it together with Federico's PRs to have just one build happening.

I still don't see the POI on my branch...

image

**Comment by lubojr** [comment]
Could you please refresh your browser cache?

I do see them on 
https://eodash-trilateral-staging.eox.at/explore?catalog=A.scremin%40starion.eu&indicator=N3a2_TSM_esa
image

**Pull request merged**
