### PR TITLE
YAML batch_6 update

### PR DESCRIPTION
**Pull request by FedericoRondoni**
N1b_PM10 N1b_PM25 N3_regional_water_quality_timeseries N3a2_chl_concentration N3a2_sea_surface_temperature N3a2_total_suspended_matter N3c_ocean_colour_plankton_atlantic N3c_ocean_colour_plankton_black_sea N3c_ocean_colour_plankton_mediterranean NASAPopulation

### CODE REVIEW

**Comment by FedericoRondoni** [comment]
Hi @santilland and @lubojr it seems that in this batch there is a new error that I cannot find. Do you have any idea of what it might be?
Thanks!

**Comment by santilland** [comment]
Hello @FedericoRondoni as far as i can tell the issue is in the NASA file collections/NASAPopulation.yaml .
The problem is, that if in yaml you use the "multiline" symbol (`|`) you need to start a new line (see also https://yaml-multiline.info/)
So, instead of:

```
Citation: | Center for International Earth Science Information Network - CIESIN - Columbia University. 2018. Gridded Population of the World, Version 4 (GPWv4): Population Density Adjusted to Match 2015 Revision UN WPP Country Totals, Revision 11. Palisades, New York: NASA Socioeconomic Data and Applications Center (SEDAC).
```
you need to do:
```
Citation: |
    Center for International Earth Science Information Network - CIESIN - Columbia University. 2018. Gridded Population of the World, Version 4 (GPWv4): Population Density Adjusted to Match 2015 Revision UN WPP Country Totals, Revision 11. Palisades, New York: NASA Socioeconomic Data and Applications Center (SEDAC).
```
or remove the multiline symbol:
```
Citation: Center for International Earth Science Information Network - CIESIN - Columbia University. 2018. Gridded Population of the World, Version 4 (GPWv4): Population Density Adjusted to Match 2015 Revision UN WPP Country Totals, Revision 11. Palisades, New York: NASA Socioeconomic Data and Applications Center (SEDAC).
```

**Comment by aapopescu** [comment]
@santilland , I finished the review, OK for me

**Comment by lubojr** [comment]
Thank you for the additions and review. Merging

**Pull request merged**
