### PR TITLE
Final indicators update

### PR DESCRIPTION
**Pull request by FedericoRondoni**
C3S_meteorological_variables E11_shopping_center_activity E11_shopping_center_volume E12b_border_crossing_vehicles_timeseries E12c_truck_detections_motorways E12d_truck_detections_primary_roads E13b_airport_throughput E13b_parked_planes E13c_cruises_impact E13d_flying_planes VED_vessel_density E200_ships_detected E3_crude_oil_storage E4_intermediate_goods_production E5_steel_inventory_timeseries OCVA_ocean_variables WAQ_water_quality NASAPopulation WSF_world_settlement_footprint CAQ_ports_air_quality E8_industrial_inventory APRO_agricultural_production AQEL_air_quality_european_level BIPS_boats_in_ports E13n_trucks_port E13c_ship_detections_algorithm GHS_BUILT-S-R2023A OX_Crude_Oil_Storage_Index OX_EU_Crude_Oil_Storage_Index GG_people_mobility_reports CV19_covid_19_indicators crop_forecast_CropOM GLP_global_parameters

### CODE REVIEW

**Comment by FedericoRondoni** [comment]
@lubojr and @santilland I'm finishing to check the aggregated indicators. I think there are one or two more, but I will write here once is done

**Comment by FedericoRondoni** [comment]
@santilland @lubojr I think it's done. This branch can be merged from my side.
Can you create a new dashboard visualisation with all the integrations I have uploaded? I want to check if I forgot any indicators outside the grouping

**Comment by lubojr** [comment]
@FedericoRondoni We have now created a whole RACE deployment (all indicators/collections in RACE.yaml) by editting the description of this PR and creating a new commit with miscellaneous changes.

You can see the testing deployment on https://eodash-testing.eox.at/ui-panels-cat/?catalog=final-indicators-update (the catalog URL query part is the name of this branch)

**Comment by FedericoRondoni** [comment]
Ok, I think we can merge everything!
Thanks @lubojr and @santilland

**Review by santilland — APPROVED** [review]
Thank you all for your work! Let's merge!

**Pull request merged**
