### PR TITLE
Update E11_shopping_center_activity.yaml

### PR DESCRIPTION
**Pull request by FedericoRondoni**
E11_shopping_center_activity

### CODE REVIEW

**Comment by FedericoRondoni** [comment]
@lubojr @santilland please merge

**Comment by santilland** [comment]
Hello @FedericoRondoni short question, are you expecting other possible updates? Would be good to do it bundled

**Comment by FedericoRondoni** [comment]
> Hello @FedericoRondoni short question, are you expecting other possible updates? Would be good to do it bundled

Hi @santilland not for now. There might be but maybe either later in the day (5:00 pm or so) or tomorrow

**Comment by santilland** [comment]
@FedericoRondoni if we don't consider this update critical i would prefer to do it after the presentation today, maybe also combined with potential other updates coming later.

**Review by santilland — APPROVED** [review]
Changes look good, let's merge

**Pull request merged**
