### PR TITLE
YAML batch_1 update

### PR DESCRIPTION
**Pull request by FedericoRondoni**
CDS1_temperature CDS2_relative_humidity

### CODE REVIEW

**Comment by FedericoRondoni** [comment]
Hi @santilland, I have added here a possible proprietary license. I added the license file as a "more information" link.
Can you please confirm that it will work in this way?

**Comment by santilland** [comment]
hi @FedericoRondoni, interesting idea, but i think we will have to handle this differently.
Going over the STAC definition i now better understand, if we set proprietary (or various) as incense type it is possible to add links to the license document. So we could.... add a CustomLicense field that could be an array for linking to any potential license documents, i think that should cover all needs.
What do you think?
The license could be described (as done in STAC by:
```
      "href": "https://example.com/license.html", # your license url
      "type": "text/html", #  or whatever media type applies
      "rel": "license",
      "title": "My cool license" # Title/Name of the license
```

**Comment by santilland** [comment]
Hello @FedericoRondoni , I have been thinking about it and adding an additional field for this seems a bit unnecessary and complicates understanding for someone providing the information, so i would propose following, the license can be either a string, with an identifier that matches one of the spdx license identifiers or it can be a list of license objects.
If only one license object is passed, then in stac it will be set to proprietary and the license added as link, if it is multiple in stac it will be set to various and all links to the licenses will be added.

So in examples the options would be:
```
License: MIT
``` 
or
```
License:
  - Url: exampleurl.com/license
    Type: text/html
    Title: Name of license
``` 
```
License:
  - Url: exampleurl.com/license1.pdf
    Type: application/pdf
    Title: Name of license 1
  - Url: exampleurl.com/license2
    Type: text/html
    Title: Name of license 2
```

**Comment by santilland** [comment]
I updated the license parsing approach to mirror the proposed changes and updated also the yaml config, from my side this would be ok to be merged

**Comment by FedericoRondoni** [comment]
Ok, I think we can merge. Should I do that?

**Comment by santilland** [comment]
I merged and I will integrate these changes in to the other branch

**Pull request merged**
